{
    "db_path": "D:\\test.db",
    "db_table": "EntityCount",
    "db_columns": [
        "AcDbEntity",
        "AcDbBlockReference",
        "AcDbMInsertBlock",
        "AcDbTable",
        "AcDbViewRepBlockReference",
        "AcDbCamera",
        "AcDbFace",
        "AcDbFcf",
        "AcDbFrame",
        "AcDbOleFrame",
        "AcDbOle2Frame",
        "AcDbHatch",
        "AcDbImage",
        "AcDbRasterImage",
        "AcDbWipeout",
        "AcDbLight",
        "AcDbMLeader",
        "AcDbMline",
        "AcDbMPolygon",
        "AcDbMText",
        "AcDbPoint",
        "AcDbPolyFaceMesh",
        "AcDbPolygonMesh",
        "AcDbProxyEntity",
        "AcDbSection",
        "AcDbShape",
        "AcDbSolid",
        "AcDbText",
        "AcDbAttribute",
        "AcDbAttributeDefinition",
        "AcDbTrace",
        "AcDbViewport",
        "AcDbCurve",
        "AcDb2dPolyline",
        "AcDb3dPolyline",
        "AcDbArc",
        "AcDbCircle",
        "AcDbEllipse",
        "AcDbLeader",
        "AcDbLine",
        "AcDbPolyline",
        "AcDbRay",
        "AcDbSpline",
        "AcDbHelix",
        "AcDbXline",
        "AcDbDimension",
        "AcDb2LineAngularDimension",
        "AcDb3PointAngularDimension",
        "AcDbAlignedDimension",
        "AcDbArcDimension",
        "AcDbDiametricDimension",
        "AcDbOrdinateDimension",
        "AcDbRadialDimension",
        "AcDbRadialDimensionLarge",
        "AcDbRotatedDimension",
        "AcDb3dSolid",
        "AcDbBody",
        "AcDbRegion",
        "AcDbSubDMesh",
        "AcDbSurface",
        "AcDbExtrudedSurface",
        "AcDbLoftedSurface",
        "AcDbNurbSurface",
        "AcDbPlaneSurface",
        "AcDbRevolvedSurface",
        "AcDbSweptSurface",
        "AcDbViewBorder",
        "AcDbViewSymbol",
        "AcDbDetailSymbol",
        "AcDbSectionSymbol",
        "AcDbUnderlayReference",
        "AcDbDgnReference",
        "AcDbDwfReference",
        "AcDbPdfReference",
        "AcDbArcAlignedText",
        "CustomEntity",
        "BlockTableRecord",
        "LayerTableRecord",
        "TextStyleTableRecord",
        "LinetypeTableRecord",
        "ViewTableRecord",
        "UCSTableRecord",
        "ViewportTableRecord",
        "RegAppTableRecord",
        "DimStyleTableRecord",
        "Color",
        "DataLink",
        "DetailViewStyle",
        "Groups",
        "Layout",
        "Material",
        "MLeaderStyle",
        "MLineStyle",
        "PlotSettings",
        "PlotStyleName",
        "ScaleList",
        "SectionViewStyle",
        "TableStyle",
        "VisualStyle",
        "DynBlockDefinition",
        "DynBlockReference",
        "AssocArray",
        "ConstraintGroup",
        "DrawingView",
        "MaxNestedBlockLevel"
    ],
    "entry_per_page": 50,
    "watched_path": "D:\\testFiles",
    "worker_time_interval": 30
}